
import Link from "next/link";
import { MathVisualization } from "@/components/MathVisualizations";
import { InteractiveMathLab } from "@/components/InteractiveMathLab";
import { RichMath } from "@/components/RichMath";
import { ScrollSpyToc } from "@/components/ScrollSpyToc";

const sections = [
  ["en-overview","Overview"],["en-review","Vector Space Review"],["en-combinations","Linear Combinations"],
  ["en-span","Span"],["en-independence","Linear Independence"],["en-basis","Basis"],["en-coordinates","Coordinates"],
  ["en-dimension","Dimension"],["en-subspaces","Subspace Bases"],["en-extension","Basis Extension"],
  ["en-row-column","Row & Column Spaces"],["en-rank-nullity","Rank–Nullity"],["en-examples","Worked Examples"],
  ["en-summary","Summary"]
] as const;

const theorems = [
  {
    n:"1", title:"Subspace Criterion",
    statement:"A nonempty subset $W\\subseteq V$ is a subspace if and only if $\\alpha u+\\beta v\\in W$ for all $u,v\\in W$ and all $\\alpha,\\beta\\in\\mathbb F$.",
    proof:[
      "If $W$ is a subspace, closure under linear combinations follows directly from the subspace axioms.",
      "Conversely, choose $w\\in W$. Setting $\\alpha=\\beta=0$ gives $0\\in W$.",
      "Setting $\\alpha=\\beta=1$ gives closure under addition; setting $\\beta=0$ gives closure under scalar multiplication.",
      "The remaining vector-space axioms are inherited from $V$, so $W$ is a subspace."
    ],
    why:"This criterion combines the usual closure checks into one compact condition."
  },
  {
    n:"2", title:"The Span Is the Smallest Subspace Containing a Set",
    statement:"For every $S\\subseteq V$, $\\operatorname{span}(S)$ is a subspace of $V$. If $W$ is any subspace containing $S$, then $\\operatorname{span}(S)\\subseteq W$.",
    proof:[
      "The zero vector belongs to the span by choosing every coefficient equal to zero.",
      "If $x=\\sum a_iv_i$ and $y=\\sum b_iv_i$ lie in the span, then $\\alpha x+\\beta y=\\sum(\\alpha a_i+\\beta b_i)v_i$ also lies in the span.",
      "Thus the span is a subspace.",
      "If $W$ contains $S$, closure under linear combinations forces every element of the span to lie in $W$."
    ],
    why:"It identifies span as the minimal subspace generated by a collection of vectors."
  },
  {
    n:"3", title:"Redundancy Criterion",
    statement:"A finite set with at least two vectors is linearly dependent if and only if one vector is a linear combination of the others.",
    proof:[
      "From a nontrivial relation $\\sum a_iv_i=0$, choose an index $j$ with $a_j\\neq0$.",
      "Solving for $v_j$ expresses it as a linear combination of the remaining vectors.",
      "Conversely, if one vector is a linear combination of the others, moving all terms to one side gives a nontrivial linear relation equal to zero."
    ],
    why:"It gives the precise meaning of redundancy in a list of vectors."
  },
  {
    n:"4", title:"Uniqueness of Representation Relative to a Basis",
    statement:"If $B=(v_1,\\ldots,v_n)$ is a basis of $V$, every $v\\in V$ has a unique representation $v=a_1v_1+\\cdots+a_nv_n$.",
    proof:[
      "Existence follows because $B$ spans $V$.",
      "If $v=\\sum a_iv_i=\\sum b_iv_i$, subtraction gives $\\sum(a_i-b_i)v_i=0$.",
      "Linear independence of $B$ gives $a_i=b_i$ for every $i$."
    ],
    why:"Unique representation is what makes coordinates relative to a basis well defined."
  },
  {
    n:"5", title:"The Coordinate Map Is an Isomorphism",
    statement:"If $B=(v_1,\\ldots,v_n)$ is a basis, the map $\\Phi_B:V\\to\\mathbb F^n$ defined by $\\Phi_B(v)=[v]_B$ is an isomorphism.",
    proof:[
      "Coordinate arithmetic shows that $\\Phi_B$ is linear.",
      "Uniqueness of basis representation makes it injective.",
      "For any $(c_1,\\ldots,c_n)\\in\\mathbb F^n$, the vector $c_1v_1+\\cdots+c_nv_n$ has those coordinates, so the map is surjective."
    ],
    why:"After choosing a basis, every $n$-dimensional vector space is algebraically equivalent to $\\mathbb F^n$."
  },
  {
    n:"6", title:"Exchange Lemma",
    statement:"If $v_1,\\ldots,v_m$ are linearly independent and $w_1,\\ldots,w_n$ span $V$, then $m\\le n$.",
    proof:[
      "Express $v_1$ as a linear combination of the spanning vectors $w_j$; at least one coefficient is nonzero.",
      "Solve for a corresponding $w_j$ and replace it by $v_1$ without changing the span.",
      "Repeat for $v_2,\\ldots,v_m$. Linear independence guarantees that another old spanning vector can be replaced at each step.",
      "The original spanning list has only $n$ vectors, so at most $n$ such replacements are possible. Hence $m\\le n$."
    ],
    why:"The Exchange Lemma is the main mechanism behind uniqueness of dimension."
  },
  {
    n:"7", title:"All Finite Bases Have the Same Size",
    statement:"If $B$ and $C$ are finite bases of $V$, then $|B|=|C|$.",
    proof:[
      "Write $|B|=m$ and $|C|=n$.",
      "Since $B$ is independent and $C$ spans, the Exchange Lemma gives $m\\le n$.",
      "Interchanging the roles of $B$ and $C$ gives $n\\le m$.",
      "Therefore $m=n$."
    ],
    why:"This theorem makes dimension a well-defined invariant of a vector space."
  },
  {
    n:"8", title:"Dimension of a Subspace",
    statement:"If $W$ is a subspace of a finite-dimensional space $V$, then $\\dim W\\le\\dim V$, with equality if and only if $W=V$.",
    proof:[
      "A basis of $W$ is a linearly independent set in $V$, so it has at most $\\dim V$ elements.",
      "If equality holds, that basis already has the maximum possible size in $V$ and is therefore a basis of $V$.",
      "Hence $W=V$. The converse is immediate."
    ],
    why:"It often proves equality of subspaces from inclusion plus equality of dimensions."
  },
  {
    n:"9", title:"Basis Extension Theorem",
    statement:"Every finite linearly independent set in a finite-dimensional vector space can be extended to a basis.",
    proof:[
      "Start with a linearly independent set $S$.",
      "If it already spans $V$, it is a basis.",
      "Otherwise choose a vector outside its span and adjoin it. The enlarged set remains independent.",
      "Repeat. The size of an independent set cannot exceed $\\dim V$, so the process stops after finitely many steps.",
      "The final set is independent and spans $V$."
    ],
    why:"Any nonredundant partial collection of directions can be completed to a full coordinate system."
  },
  {
    n:"10", title:"Reducing a Spanning Set to a Basis",
    statement:"Every finite spanning set can be reduced to a basis by deleting redundant vectors.",
    proof:[
      "If the spanning set is independent, it is already a basis.",
      "If it is dependent, the Redundancy Criterion identifies a vector lying in the span of the others.",
      "Delete that vector; the span does not change.",
      "Repeat until no redundancy remains. The final set is both independent and spanning."
    ],
    why:"This is the conceptual basis of algorithms that extract a basis from generators."
  },
  {
    n:"11", title:"Rank–Nullity Theorem",
    statement:"If $V$ is finite-dimensional and $T:V\\to W$ is linear, then $\\dim V=\\operatorname{nullity}(T)+\\operatorname{rank}(T)$.",
    proof:[
      "Take a basis $u_1,\\ldots,u_k$ of $\\ker T$.",
      "Extend it to a basis $u_1,\\ldots,u_k,v_1,\\ldots,v_r$ of $V$.",
      "The vectors $Tv_1,\\ldots,Tv_r$ span $\\operatorname{im}T$ because the kernel components vanish after applying $T$.",
      "They are independent: if $\\sum a_iTv_i=0$, then $\\sum a_iv_i\\in\\ker T$, and uniqueness in the extended basis forces all $a_i=0$.",
      "Thus rank is $r$, nullity is $k$, and the basis of $V$ has $k+r$ elements."
    ],
    why:"Rank–Nullity connects the directions a map destroys with the directions that survive in its image."
  }
];

function P({children}:{children:string}) { return <p><RichMath>{children}</RichMath></p>; }

function TheoremCard({item}:{item:(typeof theorems)[number]}) {
  return <div className="theorem-suite">
    <div className="theorem-box"><div className="box-kicker">Theorem {item.n}</div><strong>{item.title}</strong><P>{item.statement}</P></div>
    <div className="proof-box proof-detailed"><div className="box-kicker">Proof</div>{item.proof.map((step,i)=><div className="proof-step" key={step}><span>{i+1}</span><P>{step}</P></div>)}<p className="proof-end">■</p></div>
    <div className="why-box"><strong>Why is this theorem important?</strong><P>{item.why}</P></div>
  </div>;
}

export function BasisDimensionEnglish() {
  const theorem = (n:string) => theorems.find(t=>t.n===n)!;
  return <div data-no-translate>
    <section className="chapter-hero premium-chapter-hero">
      <div className="container narrow">
        <div className="breadcrumb"><Link href="/materi">Materials</Link><span>/</span><span>University</span><span>/</span><span>Linear Algebra</span><span>/</span><strong>Basis and Dimension</strong></div>
        <span className="eyebrow">Linear Algebra · University Material</span>
        <h1>Basis and Dimension</h1>
        <p>This material covers linear combinations, span, linear independence, basis, coordinates, dimension, subspace bases, row and column spaces, and Rank–Nullity.</p>
        <div className="chapter-meta"><span>University</span><span>Definitions · Theorems · Proofs</span><span>± 90–120 minutes</span><span>100 problems</span></div>
        <div className="actions"><Link className="btn primary" href="/kuliah/aljabar-linear/basis-dan-dimensi/latihan">Start Curated Practice</Link><Link className="btn secondary" href="/bank-soal/kuliah/aljabar-linear/basis-dan-dimensi">Open 100 Problems</Link></div>
      </div>
    </section>

    <section className="section">
      <div className="container article-layout wide-article-layout">
        <ScrollSpyToc
          title="Chapter Contents"
          sections={sections.map(([id, label]) => ({ id, label }))}
        />
        <article className="article deep-article basis-article">
          <section id="en-overview">
            <span className="eyebrow">Introduction</span><h2>Basis and Dimension</h2>
            <P>{String.raw`In $\\mathbb R^2$, the standard vectors $e_1=(1,0)$ and $e_2=(0,1)$ are familiar. Another pair such as $v_1=(1,1)$ and $v_2=(1,-1)$ can also represent every vector uniquely. Such a pair is a basis.`}</P>
            <P>{String.raw`A basis must be large enough to span the entire space while containing no redundant direction. Dimension measures the number of vectors required in any basis.`}</P>
            <MathVisualization kind="basis" />
            <div style={{marginTop:24}}><InteractiveMathLab kind="basis" /></div>
          </section>

          <section id="en-review"><span className="eyebrow">01 · Vector Space Review</span><h2>Vector Spaces and Subspaces</h2>
            <P>{String.raw`A vector space $V$ over a field $\\mathbb F$ supports vector addition and scalar multiplication satisfying the standard linearity axioms. Key examples are $\\mathbb R^n$, polynomial spaces $\\mathcal P_n$, matrix spaces $M_{m\\times n}(\\mathbb F)$, and function spaces.`}</P>
            <div className="definition-box"><strong>Subspace</strong><P>{String.raw`A subset $W\\subseteq V$ is a subspace if it contains $0$ and is closed under all linear combinations $\\alpha u+\\beta v$.`}</P></div>
            <div className="example-box content-box"><div className="box-kicker">Example</div><P>{String.raw`$W=\{(x,y,0):x,y\in\mathbb R\}$ is a subspace of $\mathbb R^3$.`}</P></div>
            <TheoremCard item={theorem("1")} />
          </section>

          <section id="en-combinations"><span className="eyebrow">02 · Linear Combinations</span><h2>Linear Combinations</h2>
            <div className="definition-box"><strong>Linear Combination</strong><P>{String.raw`A vector $v$ is a linear combination of $v_1,\\ldots,v_k$ if $v=a_1v_1+\\cdots+a_kv_k$ for some scalars $a_i$.`}</P></div>
            <div className="example-suite"><div className="example-box"><div className="box-kicker">Basic Example</div><strong>Is $(5,1)$ a linear combination of $(1,1)$ and $(2,-1)$?</strong></div><div className="solution-box content-box"><P>{String.raw`Solving $a(1,1)+b(2,-1)=(5,1)$ gives $a+2b=5$ and $a-b=1$, hence $b=4/3$ and $a=7/3$. Therefore the answer is yes.`}</P></div></div>
          </section>

          <section id="en-span"><span className="eyebrow">03 · Span</span><h2>Span</h2>
            <div className="definition-box"><strong>Span</strong><P>{String.raw`$\\operatorname{span}\\{v_1,\\ldots,v_k\\}$ is the set of all linear combinations $a_1v_1+\\cdots+a_kv_k$.`}</P></div>
            <div className="example-box content-box"><div className="box-kicker">Example</div><P>{String.raw`The span of $(1,0,0)$ and $(0,1,0)$ is the plane $z=0$ in $\mathbb R^3$.`}</P></div>
            <TheoremCard item={theorem("2")} />
            <div className="counterexample-box content-box"><strong>Important counterexample</strong><P>{String.raw`In $\\mathbb R^3$, the set $\\{(1,0,0),(0,1,0)\\}$ does not span the whole space because every combination has third coordinate zero.`}</P></div>
          </section>

          <section id="en-independence"><span className="eyebrow">04 · Linear Independence</span><h2>Linear Independence</h2>
            <div className="definition-box"><strong>Linear Independence</strong><P>{String.raw`The vectors $v_1,\\ldots,v_k$ are linearly independent if $a_1v_1+\\cdots+a_kv_k=0$ implies $a_1=\\cdots=a_k=0$.`}</P></div>
            <div className="example-box content-box"><div className="box-kicker">Example</div><P>{String.raw`The vectors $(1,0)$ and $(0,1)$ are linearly independent, while $(1,0)$ and $(2,0)$ are linearly dependent.`}</P></div>
            <TheoremCard item={theorem("3")} />
            <div className="comparison-table"><div className="comparison-col"><span className="eyebrow">Independent</span><strong>No redundancy</strong><p>Only the trivial relation gives zero.</p></div><div className="comparison-col"><span className="eyebrow">Dependent</span><strong>Redundant information</strong><p>At least one vector lies in the span of the others.</p></div></div>
          </section>

          <section id="en-basis"><span className="eyebrow">05 · Basis</span><h2>Basis</h2>
            <div className="definition-box"><strong>Basis</strong><P>{String.raw`A set $B$ is a basis of $V$ when it is linearly independent and $\\operatorname{span}(B)=V$.`}</P></div>
            <div className="example-box content-box"><div className="box-kicker">Example</div><P>{String.raw`The standard vectors $(1,0)$ and $(0,1)$ form a basis of $\mathbb R^2$.`}</P></div>
            <TheoremCard item={theorem("4")} />
            <div className="example-suite"><div className="example-box"><strong>A nonstandard basis of $\\mathbb R^2$</strong><P>{String.raw`For $B=((1,1),(1,-1))$, find $[(4,2)]_B$.`}</P></div><div className="solution-box content-box"><P>{String.raw`Solving $a(1,1)+b(1,-1)=(4,2)$ gives $a=3$, $b=1$. Hence $[(4,2)]_B=(3,1)$.`}</P></div></div>
          </section>

          <section id="en-coordinates"><span className="eyebrow">06 · Coordinates</span><h2>Coordinates Relative to a Basis</h2>
            <P>{String.raw`If $B=(v_1,\\ldots,v_n)$ is ordered and $v=a_1v_1+\\cdots+a_nv_n$, then $[v]_B=(a_1,\\ldots,a_n)^T$.`}</P>
            <div className="example-box content-box"><div className="box-kicker">Example</div><P>{String.raw`Relative to the standard basis $E$, the vector $(3,-2)$ has coordinate vector $(3,-2)^T$.`}</P></div>
            <TheoremCard item={theorem("5")} />
          </section>

          <section id="en-dimension"><span className="eyebrow">07 · Dimension</span><h2>Dimension</h2>
            <div className="definition-box"><strong>Dimension</strong><P>{String.raw`If $V$ has a finite basis with $n$ elements, define $\\dim V=n$. Also $\\dim\\{0\\}=0$.`}</P></div>
            <div className="example-box content-box"><div className="box-kicker">Example</div><P>{String.raw`The polynomial space $\mathcal P_2$ has basis $\{1,x,x^2\}$, hence $\dim\mathcal P_2=3$.`}</P></div>
            <TheoremCard item={theorem("6")} /><TheoremCard item={theorem("7")} />
            <div className="dimension-facts"><div><strong><RichMath>{String.raw`$\\dim\\mathbb R^n=n$`}</RichMath></strong><span>the standard basis has n vectors</span></div><div><strong><RichMath>{String.raw`$\\dim\\mathcal P_n=n+1$`}</RichMath></strong><span>basis 1, x, ..., x^n</span></div><div><strong><RichMath>{String.raw`$\\dim M_{m\\times n}=mn$`}</RichMath></strong><span>one matrix unit per entry</span></div></div>
          </section>

          <section id="en-subspaces"><span className="eyebrow">08 · Subspace Bases</span><h2>Subspace Bases and Dimension</h2>
            <TheoremCard item={theorem("8")} />
            <div className="example-suite"><div className="example-box"><strong>A plane in $\\mathbb R^3$</strong><P>{String.raw`Find a basis of $W=\\{(x,y,z):x+y+z=0\\}$.`}</P></div><div className="solution-box content-box"><P>{String.raw`Since $z=-x-y$, $(x,y,z)=x(1,0,-1)+y(0,1,-1)$. The two generators are independent, so they form a basis and $\\dim W=2$.`}</P></div></div>
          </section>

          <section id="en-extension"><span className="eyebrow">09 · Basis Extension</span><h2>Basis Extension</h2><TheoremCard item={theorem("9")} /><TheoremCard item={theorem("10")} /></section>

          <section id="en-row-column"><span className="eyebrow">10 · Row & Column Spaces</span><h2>Row and Column Spaces</h2>
            <P>{String.raw`For $A\\in\\mathbb F^{m\\times n}$, the row space is the span of the rows and the column space is the span of the columns.`}</P>
            <div className="content-box idea-box"><strong>Computational Rule</strong><p>Nonzero rows of an echelon form form a basis of the row space. For the column space, use the pivot positions found by row reduction but select the corresponding columns from the original matrix.</p></div>
          </section>

          <section id="en-rank-nullity"><span className="eyebrow">11 · Rank–Nullity</span><h2>Rank–Nullity Theorem</h2>
            <div className="definition-box"><strong>Rank and Nullity</strong><P>{String.raw`For $T:V\\to W$, $\\operatorname{rank}(T)=\\dim(\\operatorname{im}T)$ and $\\operatorname{nullity}(T)=\\dim(\\ker T)$.`}</P></div>
            <div className="example-box content-box"><div className="box-kicker">Example</div><P>{String.raw`For $T(x,y,z)=(x,y)$, $\operatorname{rank}T=2$ and $\operatorname{nullity}T=1$.`}</P></div>
            <TheoremCard item={theorem("11")} />
            <div className="content-box insight-box"><strong>Important consequence</strong><P>{String.raw`For $T:V\\to V$ on a finite-dimensional space, injectivity is equivalent to surjectivity. Injectivity gives nullity zero; Rank–Nullity then gives full rank, hence surjectivity.`}</P></div>
          </section>

          <section id="en-examples"><span className="eyebrow">12 · Worked Examples</span><h2>Worked Examples</h2>
            <div className="example-stack">
              <div className="example-suite"><div className="example-box"><div className="box-kicker">Basic</div><strong>Dimension of a span</strong><P>{String.raw`Find $\\dim\\operatorname{span}\\{(1,0,1),(0,1,1),(1,1,2)\\}$.`}</P></div><div className="solution-box content-box"><p>The third vector is the sum of the first two. The first two are independent, so the dimension is 2.</p></div></div>
              <div className="example-suite"><div className="example-box"><div className="box-kicker">Intermediate</div><strong>Basis of a solution space</strong><P>{String.raw`Solve $x+y+z+w=0$ and $x-z=0$.`}</P></div><div className="solution-box content-box"><P>{String.raw`We obtain $z=x$ and $y=-2x-w$, so every solution equals $x(1,-2,1,0)+w(0,-1,0,1)$. The two vectors form a basis.`}</P></div></div>
              <div className="example-suite"><div className="example-box"><div className="box-kicker">Advanced</div><strong>Dimension formula for two subspaces</strong><P>{String.raw`Prove $\\dim(U+W)=\\dim U+\\dim W-\\dim(U\\cap W)$.`}</P></div><div className="solution-box content-box"><p>Start with a basis of the intersection, extend it separately to bases of U and W, then show that the combined nonduplicated list is a basis of U+W. Counting basis vectors gives the formula.</p></div></div>
            </div>
          </section>

          <section id="en-summary"><span className="eyebrow">13 · Summary</span><h2>Main Results</h2>
            <div className="summary-grid">{[
              ["Span","The smallest subspace containing the generators."],["Linear Independence","No redundant direction."],["Basis","Independent and spanning."],["Coordinates","Unique representation relative to a basis."],["Dimension","The common size of every finite basis."],["Basis Extension","Independent sets can be completed to bases."],["Subspaces","Subspace dimension cannot exceed ambient dimension."],["Rank–Nullity","Domain dimension = rank + nullity."]
            ].map(([t,b])=><div className="summary-card" key={t}><strong>{t}</strong><p>{b}</p></div>)}</div>
            <div className="actions"><Link className="btn primary" href="/kuliah/aljabar-linear/basis-dan-dimensi/latihan">Work Through Curated Practice</Link><Link className="btn secondary" href="/bank-soal/kuliah/aljabar-linear/basis-dan-dimensi">Open 100 Problems</Link></div>
          </section>
        </article>
      </div>
    </section>
  </div>;
}
