export const siteConfig = {
  name: "DMath Learning",
  shortName: "DMath",
  tagline: "Think Deeper, Solve Better.",
  description:
    "DMath Learning adalah platform pembelajaran matematika berbahasa Indonesia untuk memahami konsep, pembuktian, latihan, bank soal, ON-MIPA, dan matematika universitas.",
  url: "https://dmath-learning.vercel.app",
  locale: "id_ID",
  language: "id-ID",
  ogImage: "/opengraph-image",
  social: {
    youtube: "https://www.youtube.com/@DMathLearning",
  },
  keywords: [
    "DMath Learning",
    "belajar matematika",
    "materi matematika",
    "bank soal matematika",
    "ON-MIPA matematika",
    "ON-MIPA matematika",
    "matematika kuliah",
    "analisis real",
    "aljabar linear",
    "analisis kompleks",
    "analisis numerik",
    "probabilitas",
    "teori ukuran",
    "kalkulus stokastik",
    "riset operasi",
    "statistika terapan",
    "statistika matematika",
    "matematika diskrit",
  ],
  nav: [
    { label: "Beranda", href: "/" },
    { label: "Materi", href: "/materi" },
    { label: "Bank Soal", href: "/bank-soal" },
    { label: "ON-MIPA", href: "/olimpiade" },
    { label: "Latihan Soal", href: "/latihan-soal" },
    { label: "Sumber Belajar Lain", href: "/sumber-belajar-lain" },
    { label: "Tentang", href: "/tentang" },
  ],
} as const;
